# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170301_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlabel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventlabel',
            name='label',
        ),
        migrations.AddField(
            model_name='event',
            name='labels',
            field=models.ManyToManyField(related_name='events', to='events.Label'),
        ),
        migrations.DeleteModel(
            name='EventLabel',
        ),
    ]
