# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170302_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
