# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='period',
        ),
    ]
