# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.DurationField(null=True),
        ),
    ]
