# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
